"""First Migration1

Revision ID: 84d9fde7c54a
Revises: 
Create Date: 2024-03-24 21:56:08.627785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d9fde7c54a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('cart', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'IN_PROGRESS', 'PAID', name='usercartstatus'), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'APPROVED', 'REJECTED', name='contractstatus'), nullable=False),
    sa.Column('user_limit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('assigment_of_rights', sa.Boolean(), nullable=True),
    sa.Column('general_terms', sa.Boolean(), nullable=True),
    sa.Column('wanted_limit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ali_user_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'APPROVED', 'REJECTED', name='userstatus'), nullable=False),
    sa.Column('registration_address', sa.String(), nullable=True),
    sa.Column('monthly_income', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ali_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_contracts')
    op.drop_table('user_carts')
    # ### end Alembic commands ###
